# Generated using https://godot-build-options-generator.github.io

extra_suffix = "moye"
dev_build = "no"
winrt = "no"
accesskit = "no"
use_mingw = "yes"
use_llvm = "yes"

# production = "yes"
# disable_3d = "yes"
# optimize = "size"
# lto = "full"
# disable_physics_2d = "yes"
# disable_physics_3d = "yes"

optimize = "size_extra"

module_basis_universal_enabled = "no"
module_bmp_enabled = "no"
module_camera_enabled = "no"
module_fbx_enabled = "no"
module_theora_enabled = "no"
module_csg_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gltf_enabled = "no"
module_gridmap_enabled = "no"
module_ktx_enabled = "no"
module_meshoptimizer_enabled = "no"
module_mobile_vr_enabled = "no"
module_multiplayer_enabled = "no"
module_navigation_enabled = "no"
module_openxr_enabled = "no"
module_raycast_enabled = "no"
module_squish_enabled = "no"
module_text_server_adv_enabled = "no"
module_text_server_fb_enabled = "yes"
module_tga_enabled = "no"
module_vhacd_enabled = "no"
module_vorbis_enabled = "no"
module_webrtc_enabled = "no"
