#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_godot_gif = env_modules.Clone()
env_godot_gif.Prepend(CPPPATH=["#modules/godot_gif"])

thirdparty_obj = []
thirdparty_sources = [
    "thirdparty/giflib-5.2.2/dgif_lib.c",
    "thirdparty/giflib-5.2.2/egif_lib.c",
    "thirdparty/giflib-5.2.2/gifalloc.c",
    "thirdparty/giflib-5.2.2/gif_err.c",
    "thirdparty/giflib-5.2.2/gif_hash.c",
    "thirdparty/giflib-5.2.2/openbsd-reallocarray.c",
    "thirdparty/giflib-5.2.2/quantize.c",
]

env_giflib = env_godot_gif.Clone()
env_giflib.disable_warnings()
env_giflib.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

module_obj = []
env_godot_gif.add_source_files(module_obj, "*.cpp")
env_godot_gif.add_source_files(module_obj, "core/*.cpp")
env_godot_gif.add_source_files(module_obj, "node/*.cpp")

if env.editor_build:
    env_godot_gif.add_source_files(module_obj, "editor/*.cpp")

env.modules_sources += module_obj

env.Depends(module_obj, thirdparty_obj)
